import {
  CONTACT_QUOTE_EMAIL_PLACEHOLDER,
  CONTACT_QUOTE_MESSAGE_PLACEHOLDER,
  CONTACT_QUOTE_NAME_PLACEHOLDER,
} from "@/lib/email-template-placeholders";

export const MERCH_QUOTE_DEFAULT_SUBJECT_TEMPLATE = `Merch website quote — ${CONTACT_QUOTE_NAME_PLACEHOLDER}`;

export const MERCH_QUOTE_DEFAULT_TEXT_TEMPLATE = `Merch website quote request

Name: ${CONTACT_QUOTE_NAME_PLACEHOLDER}
Email: ${CONTACT_QUOTE_EMAIL_PLACEHOLDER}

${CONTACT_QUOTE_MESSAGE_PLACEHOLDER}`;
