// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import {
  migrateDirectUrlFromEnv,
  runtimeDatabaseUrlFromEnv,
} from "./src/lib/env-postgres-url";

/**
 * URL used by Prisma CLI (`migrate deploy`, etc.).
 * Prefer a direct (non-pooled) URL — required for Neon poolers and Vercel Postgres migrations.
 */
function migrateDatabaseUrl(): string | undefined {
  const direct = migrateDirectUrlFromEnv();
  if (direct) return direct;
  return runtimeDatabaseUrlFromEnv();
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: migrateDatabaseUrl(),
  },
});
